.TH NEON 1 "18 May 23"
.SH NAME
neon \- A simple project revision tracker
.SH SYNOPSIS 
.TP
\fbneon\fp [command] [arguments]
.SH DESCRIPTION
NEON is a package of programs to track revisions within a file and/or project.
It's usually meant for source code management but it can also be used on any
ASCII text files.
.SH AUTHOR
NEON was written by Ariston Lorenzo.
Copyright (c) 2023 Ariston Lorenzo. All rights reserved.
See the source tree for more information.
.SH BUGS
Most features of modern version control systems aren't implemented yet and
current functions may not work as expected.
