E=@echo
Q=@

install:
	$(Q) install -d -m 755 '$(PREFIX)/share/neon/templates'
	$(E) "  ==> INSTALL		templates"
	$(Q) install -m 755 config '$(PREFIX)/share/neon/templates'
	$(E) "  ==> INSTALL		templates/config"
